language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - pip install .
script:
  - python -m unittest discover

  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then ./shellpy example/test.spy;  fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then ./shellpy example/test3.spy; fi